### ISSUE TITLE
create "Sketch" and "Capture screenshot" components in reactjs

### ISSUE THREAD

**Issue by rpateld** [tomwayson/esri-loader-hooks#33]
Can you please create "Sketch" and "Capture screenshot" components? 

Sketch widget: https://developers.arcgis.com/javascript/latest/sample-code/sketch-geometries/
Capture Screenshot: https://developers.arcgis.com/javascript/latest/sample-code/sceneview-screenshot/

**Comment by tomwayson** [comment]
no
